name = "clfjl"
uuid = "eafa427e-4a75-4cbf-a012-f355c2779cbe"
authors = ["guberger <guillaume.berger@colorado.edu>"]
version = "0.1.0"

[deps]
Gurobi = "2e9cd046-0924-5485-92f1-d5272153d98b"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"
PyPlot = "d330b81b-6aea-500a-939a-2ce795aea3ee"
