name = "clfjl"
uuid = "eafa427e-4a75-4cbf-a012-f355c2779cbe"
authors = ["watakandai <kandai.wata@gmail.com>"]
version = "0.1.0"

[deps]
Deldir = "64db5801-a3ae-51a7-b7d2-a0a5f0813e47"
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
GeometricalPredicates = "fd0ad045-b25c-564e-8f9c-8ef5c5f21267"
GeometryBasics = "5c1252a2-5f33-56bf-86c9-59e7332b4326"
Gurobi = "2e9cd046-0924-5485-92f1-d5272153d98b"
IterTools = "c8e1da08-722c-5040-9ed9-7db0dc04731e"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
OSQP = "ab2f91bb-94b4-55e3-9ba0-7f65df51de79"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"
PyPlot = "d330b81b-6aea-500a-939a-2ce795aea3ee"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
Suppressor = "fd094767-a336-5f1f-9728-57cf17d0bbfb"
VoronoiCells = "e3e34ffb-84e9-5012-9490-92c94d0c60a4"
VoronoiDelaunay = "72f80fcb-8c52-57d9-aff0-40c1a3526986"
YAML = "ddb6d928-2868-570f-bddf-ab3f9cf99eb6"
