runTime: 2
numStateDim: 3
numSpaceDim: 2
startThreshold: 0.10
goalThreshold: 0.10
start: [-0.75, 0.75, 0]
goal: [0.75, -0.75, 0]
lowerBound: [-1, -1]
upperBound: [1, 1]
controlDurationBound: [1, 1]
propagationStepSize: 1
planner: "SST"
# objective: "PathClearance"
objective: "WeightedLengthAndClearanceCombo"
file: "path.txt"
obstacles:
  -
    type: "Square"
    x: -0.5
    y: 0.2
    l: 0.3
  -
    type: "Square"
    x: 0.5
    y: -0.2
    l: 0.3

dynamics:
  1:
    A: [[1, 0, 0],
        [0, 1, 0],
        [0, 0, 0]]
    b: [0.125, 0, 0]
  2:
    A: [[1, 0, 0],
        [0, 1, 0],
        [0, 0, 0]]
    b: [0, 0.125, 1.570795]
  3:
    A: [[1, 0, 0],
        [0, 1, 0],
        [0, 0, 0]]
    b: [-0.125, 0, 3.14159]
  4:
    A: [[1, 0, 0],
        [0, 1, 0],
        [0, 0, 0]]
    b: [0, -0.125, -1.570795]
